language: go

sudo: false

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - tip

matrix:
  allow_failures:
    - go: master
fast_finish: true

script:
  - ./.travis.gogenerate.sh
  - ./.travis.gofmt.sh
  - ./.travis.govet.sh
  - go test -v -race $(go list ./... | grep -v vendor)
