language: go

sudo: false

go:
  - 1.7
  - 1.8
  - 1.9
  - tip

script:
  - ./.travis.gogenerate.sh
  - ./.travis.gofmt.sh
  - ./.travis.govet.sh
  - go test -v -race $(go list ./... | grep -v vendor)
