package suite

import "testing"

// TestingSuite can store and return the current *testing.T context
// generated by 'go test'.
type TestingSuite interface {
	T() *testing.T
	SetT(*testing.T)
}

// BeforeAllSuite has a BeforeSuite method, intended to be run before
// the entire suite is tested.
type BeforeAllSuite interface {
	BeforeSuite()
}

// BeforeTestSuite has a BeforeTest method, intended to be run before
// each test.
type BeforeTestSuite interface {
	BeforeTest()
}

// AfterAllSuite has an AfterSuite method, intended to be run after the
// entire suite has been tested.
type AfterAllSuite interface {
	AfterSuite()
}

// AfterTestSuite has an AfterTest method, intended to be run after
// each test.
type AfterTestSuite interface {
	AfterTest()
}
