name: All builds
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          # Our developer environment (especially the code generator)
          # must work with all the supported Go releases.
          - stable
          - oldstable
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go_version }}
      - run: ./.ci.gogenerate.sh
      - run: ./.ci.gofmt.sh
      - run: ./.ci.govet.sh

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version:
          # Tested version are ordered for faster useful feedback:
          # 'stable' and 'oldstable' are the most important
          # then the oldest supported version from go.mod
          # then the other intermediary Go versions (which, at this point
          # have low chance to fail if the other succeeded)
          - stable
          - oldstable
          - "1.17"
          - "1.18"
          - "1.19"
          - "1.20"
          - "1.21"
          - "1.22"
          - "1.23"
          - "1.24"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Go
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go_version }}
      - name: Test
        run: go test -v -race ./...

  check-actions-hashes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - run: ./.ci.ghactions.sh
